import { Types } from "mongoose";
import { HistoryModel } from "./schema/history";

/**
 * Get total number of summaries generated by user across all types
 * @param userId 
 * @returns count
 */
export const getTotalSummaryCountByUserId = async (userId: string | Types.ObjectId) => {
  try {
    const count = await HistoryModel.countDocuments({ 
      userId: typeof userId === 'string' ? new Types.ObjectId(userId) : userId 
    });
    return count;
  } catch (error) {
    console.error("Error getting total summary count:", error);
    return 0;
  }
};
